"""Shared constants for VaultX."""

from __future__ import annotations

from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
DATA_DIR = ROOT_DIR / "data"
VAULT_DIR = ROOT_DIR / "Vault"
LOG_DIR = ROOT_DIR / "logs"
CONFIG_FILE = DATA_DIR / "config.json"
VAULT_FILE = DATA_DIR / "vault.dat"
TEMP_VAULT_FILE = DATA_DIR / "vault.tmp"
BACKUP_VAULT_FILE = DATA_DIR / "vault.bak"
LOG_FILE = LOG_DIR / "vault.log"
ITERATIONS = 600_000
APP_VERSION = "2.1.0"
MIN_PASSWORD_LENGTH = 8

CREATE_NEW_VAULT_MESSAGE = "Create New Vault"
LOCK_VAULT_MESSAGE = "[1] Lock Vault"
UNLOCK_VAULT_MESSAGE = "[1] Unlock Vault"
RECOVERY_TITLE = "--------------------------------"
RECOVERY_MESSAGE = "Recovery detected"
RECOVERY_RECOVER_OPTION = "[1] Recover previous operation"
RECOVERY_DELETE_OPTION = "[2] Delete temporary file"
RECOVERY_PROMPT = "Choose option [1-2]: "
RECOVER_OPTION = "1"
DELETE_TEMP_OPTION = "2"
ENTER_TO_CONTINUE_PROMPT = "Press ENTER to continue: "
CREATE_PASSWORD_PROMPT = "Create Password: "
CONFIRM_PASSWORD_PROMPT = "Confirm Password: "
PASSWORD_PROMPT = "Password: "
PASSWORDS_DO_NOT_MATCH = "Passwords do not match."
PASSWORD_TOO_SHORT = "Password too short."
STARTUP_MESSAGE = "VaultX %s started."
SHUTDOWN_MESSAGE = "VaultX shutting down."
OPERATION_CANCELLED = "Operation cancelled."
LOCKED_MESSAGE = "Vault locked."
UNLOCKED_MESSAGE = "Vault unlocked."
TEMP_FILE_DELETED = "Temporary vault file deleted."
BACKUP_RESTORED = "Backup restored."
BACKUP_REMOVED = "Backup removed."
BACKUP_CREATED = "Backup created."
VAULT_FOLDER_NOT_FOUND = "Vault folder not found."
NO_VAULT_FOUND = "No vault found."
VAULT_ALREADY_UNLOCKED = "Vault is already unlocked."
WRONG_PASSWORD_OR_CORRUPTED = "Wrong password or corrupted vault."
VAULT_CREATION_FAILED = "Vault creation failed."
LOCK_FAILED = "Failed to lock vault: %s"
UNLOCK_FAILED = "Failed to unlock vault: %s"
RECOVERY_FAILED = "Recovery failed: %s"
RECOVERY_COMPLETE = "Recovery complete."
TEMP_FILE_MISSING = "Temporary vault file not found."
